# Generated by Django 4.0.4 on 2022-06-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='dia',
        ),
        migrations.AddField(
            model_name='agenda',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de perfil', null=True, upload_to='imgs/profile_user', verbose_name='foto'),
        ),
    ]
