# Generated by Django 4.0.4 on 2022-06-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_agendamento_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarios',
            name='dia',
            field=models.DateField(default=1, verbose_name='dia'),
            preserve_default=False,
        ),
    ]
