# Generated by Django 4.0.4 on 2022-06-27 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_horarios_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarios',
            name='dia',
        ),
    ]
